Some updates with feature send_task
ProCharity/ProCharity_bot pull request #34
Opened 2022-10-22 10:09 UTC by AbramovMax

Переименовал метод send_task в preparing_tasks_for_send.

Переименовал константу NUMBER_USERS_TO_SEND в MAILING_BATCH_SIZE.

Поменял логику отправки сообщений в чаты Телеграм. Для этого  в preparing_tasks_for_send при подготовки сообщений объявил переменную send_time и задал ее текущим временем в местном часовом поясе. При отправке каждого сообщения прибавлял к ней по 1 секунде и передавал в send_new_tasks.
Там к ней добавил значения счетчик чатов и снова вернул ее в preparing_tasks_for_send.
Это позволило добиться отправки каждого сообщения раз в секунду в n чатов (MAILING_BATCH_SIZE) и избавиться от ошибок типа:
`2022-10-20 15:22:53,285	WARNING	connectionpool.py:275	Connection pool is full, discarding connection: api.telegram.org`

2022-10-23 20:29 UTC, AntonZelinsky requested changes
Дальше не пишу, так как по фидбекам будет переписана большая часть алгоритма.

2022-10-23 20:29 UTC, AntonZelinsky commented on bot/messages.py
> +        for i, part in enumerate(self.__split_chats(send_to, config.MAILING_BATCH_SIZE)):
Что значит `i` и что значит `part?`

2022-10-23 20:29 UTC, AntonZelinsky commented on app/webhooks/tasks.py
>          if task_to_send:
Тут нужно сделать инверсию

2022-10-23 20:29 UTC, AntonZelinsky commented on app/webhooks/tasks.py
>                      if task.category_id in [cat.id for cat in user.categories]:
Избавляемся от сокращений. И от третьего вложенного цикла который делает одну и туже работу на каждой итерации двух вложенных циклов.
`[cat.id for cat in user.categories]`
Правда как это просто сделать я пока не знаю. Тут главная проблема, что при обращении к `user.categories` идёт запрос к базе данных, а значит, что для каждой задачи, мы сделаем как минимум `len(users)` запросов, что на базе данных из 1000 пользователей существенная нагрузка. А если задачи 2, то это уже 2000 запросов. Нужно как-то кэшировать.

Как вариант, можно делать sql запрос для каждой задачи, на получение пользователей кому нужно отправить сообщение, тогда, количество запросов к базе сократится до 1-го в лучшем случае. То есть, мы должны сделать запрос на получение пользователей к которых включена рассылка и они подписаны на категорию задачи. Как итог, 1 задача, один запрос.
Если я не прав, то поправьте меня.

2022-10-24 21:51 UTC, kr0t requested changes

2022-10-24 21:51 UTC, kr0t commented on app/webhooks/tasks.py
>          logger.info(f"Tasks: Tasks passed to the send_task method - {[(task.id, task.title) for task in task_to_send]}")
Так как изменилось название метода, сообщение лога надо тоже изменить.

2022-10-24 21:51 UTC, kr0t commented on app/webhooks/tasks.py
>              users = User.query.options(load_only('telegram_id')).filter_by(has_mailing=True).all()
@AntonZelinsky может стоит вынести это в отдельный метод + это относится к слою данных, и тут этого быть не должно, что думаешь?

2022-10-24 21:51 UTC, kr0t commented on app/webhooks/tasks.py
>                  chats_list = []
Название не соответствует содержимому, что за чаты? Там же находятся юзеры.

2022-10-24 21:51 UTC, kr0t commented on app/webhooks/tasks.py
>                      if task.category_id in [cat.id for cat in user.categories]:
Соглашусь с предложенным вариантом и как писал выше, думаю стоит это вынести в отдельный метод, т.к. тут происходит получение данных.

2022-10-24 21:51 UTC, kr0t commented on app/webhooks/tasks.py
> +                    send_time = notification.send_new_tasks(message=display_task_notification(task), send_to=chats_list, send_time=send_time)
А зачем тут нужно присваивать результат, ведь ты дальше его нигде не используешь?

2022-10-24 21:51 UTC, kr0t commented on app/webhooks/tasks.py
> +                    send_time = send_time + datetime.timedelta(seconds=1)
Для чего нужна эта переменная `send_time` если в методе `send_new_tasks` ты определяешь точно такую же и так же прибавляешь секунду?

2022-10-25 01:33 UTC, AbramovMax commented on bot/messages.py
> +        for i, part in enumerate(self.__split_chats(send_to, config.MAILING_BATCH_SIZE)):
i - счетчик цикла
part - пачка чатов, которая определяется переменной MAILING_BATCH_SIZE.

Дам этим переменным более подходящие названия.

2022-10-25 01:46 UTC, AbramovMax commented on app/webhooks/tasks.py
> +                    send_time = notification.send_new_tasks(message=display_task_notification(task), send_to=chats_list, send_time=send_time)
Чтобы сообщения не отсылались в один момент я распределяю их по времени.
Для этого я беру текущее время `send_time = datetime.datetime.now(pytz.utc)` и прибавляю по 1 секунде каждую итерацию цикла `for task in task_to_send:`
Это позволяет добиться того чтобы каждое сообщение уходило в свое время, но одно сообщение может уйти больше чем одному юзеру.
Поэтому я прибавляю еще по секунде каждую итерацию цикла в методе `send_new_task`. После этого у переменной `send_time` изменяется значение и если не вернуть ее в метод `preparing_tasks_for_send`, то следующее сообщение снова отправиться в текущее время + 1.

2022-10-25 01:47 UTC, AbramovMax commented on app/webhooks/tasks.py
> +                    send_time = send_time + datetime.timedelta(seconds=1)
В методе `send_new_tasks` я получаю эту переменную с уже прибавленной секундой.
Это позволяет добиться того чтобы каждое сообщение уходило в свое время, но одно сообщение может уйти больше чем одному юзеру.
Поэтому я прибавляю еще по секунде каждую итерацию цикла в методе send_new_task. После этого у переменной send_time изменяется значение и если не вернуть ее в метод preparing_tasks_for_send, то следующее сообщение снова отправиться в текущее время + 1.

2022-10-25 01:53 UTC, AbramovMax commented on app/webhooks/tasks.py
>                  chats_list = []
Подберу более подходящее название.

2022-10-25 08:37 UTC, AbramovMax commented on app/webhooks/tasks.py
>          if task_to_send:
Не совсем понял про инверсию.(
Ты имеешь ввиду `if  not task_to_send:` ?

2022-10-25 17:36 UTC, AntonZelinsky commented on app/webhooks/tasks.py
>          if task_to_send:
Да и выход из функции, чтобы не было вложенности

2022-10-25 17:37 UTC, AntonZelinsky commented on app/webhooks/tasks.py
>              users = User.query.options(load_only('telegram_id')).filter_by(has_mailing=True).all()
Да, сделаем. Смержим это и начинаем выносить всё в отдельные методы и классы

2022-10-25 17:38 UTC, AntonZelinsky commented on bot/messages.py
> +        for i, part in enumerate(self.__split_chats(send_to, config.MAILING_BATCH_SIZE)):
Но так и не дал, пока не запушишь изменения, не нужно помечать как выполненные фидбеки.
+ Строкой выше удали пустую строку

2022-10-26 01:11 UTC, AbramovMax commented on app/webhooks/tasks.py
>                      if task.category_id in [cat.id for cat in user.categories]:
А разве идет обращение к базе данных тут `user.categories`?
Мы же здесь получили юзеров из базы `users = User.query.options(load_only('telegram_id')).filter_by(has_mailing=True).all()`, разве это не обращение к объекту?

2022-10-26 01:13 UTC, AbramovMax commented on app/webhooks/tasks.py
>              users = User.query.options(load_only('telegram_id')).filter_by(has_mailing=True).all()
@AntonZelinsky , Мне нужно вынести работу с юзерами в отдельный метод в рамках этой задачи? Или это уже будет отдельная задача?

2022-10-26 21:02 UTC, kr0t commented on app/webhooks/tasks.py
>                      if task.category_id in [cat.id for cat in user.categories]:
В таблице `Category` определена связь пользователей с категориями через другую таблицу: 
`users = relationship('User', secondary='users_categories', backref=backref('categories'))`

2022-10-26 21:06 UTC, kr0t commented on app/webhooks/tasks.py
>              users = User.query.options(load_only('telegram_id')).filter_by(has_mailing=True).all()
@AbramovMax это будет отдельной задачей, сейчас необходимо внести правки по комментариям и смержить ПР.

2022-10-27 07:55 UTC, AbramovMax commented
Переименовал переменные:
i - chats_count,
part - chats_set

Избавился от третьего цикла в методе preparing_tasks_for_send.
Добавил инверсию и выход из функции:
`if not task_to_send:
            logger.info("Tasks: No tasks to send")
            return`

2022-10-27 07:56 UTC, AbramovMax commented on app/webhooks/tasks.py
>                      if task.category_id in [cat.id for cat in user.categories]:
Убрал третий цикл.

2022-10-27 07:56 UTC, AbramovMax commented on app/webhooks/tasks.py
>          if task_to_send:
Сделал инверсию и выход из функции.

2022-10-27 07:56 UTC, AbramovMax commented on bot/messages.py
> +        for i, part in enumerate(self.__split_chats(send_to, config.MAILING_BATCH_SIZE)):
Исправил.

2022-10-27 09:28 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +            return
Вроде как логирование нужно поменять местами с if, так как первый лог не имеет смысла.

2022-10-27 21:05 UTC, kr0t commented on app/webhooks/tasks.py
> +                if user.has_mailing == True:
Сравнение с True избыточно, достаточно `if user.has_mailing:`

2022-10-28 09:14 UTC, AbramovMax commented on app/webhooks/tasks.py
> +            return
Поменял.

2022-10-28 09:15 UTC, AbramovMax commented on app/webhooks/tasks.py
> +                if user.has_mailing == True:
Убрал.

2022-10-29 07:50 UTC, AbramovMax commented
Убрал лишнюю операцию по прибавлению секунды.
Ошибка переполнения пулла сообщений не воспроизводится при одном пост-запросе.

2022-11-01 09:25 UTC, AbramovMax commented
Перенес  блок с try  в отдельный приватный метод и добавил retry-паттерн.

Остальные просьбы выполнить не могу, все в слаке описал https://practicum-students.slack.com/archives/C024ZMV8M41/p1667124505932179?thread_ts=1666089120.631939&cid=C024ZMV8M41

2022-11-01 09:27 UTC, AbramovMax commented on app/webhooks/tasks.py
> +                    send_time = send_time + datetime.timedelta(seconds=1)
Убрал. Лишняя операция.

2022-11-01 22:50 UTC, AntonZelinsky commented on bot/messages.py
> +                    logger.error(f'{str(ex.message)}, telegram_id: {user.telegram_id}')
Логировать нужно всегда

2022-11-01 22:51 UTC, AntonZelinsky commented on bot/messages.py
> +                    logger.error(f'{str(ex.message)}, telegram_id: {user.telegram_id}')
И паузу делай после неудачных попыток. Какая итерация, столько секунд и жди

2022-11-02 08:18 UTC, AbramovMax commented on bot/messages.py
> +                    logger.error(f'{str(ex.message)}, telegram_id: {user.telegram_id}')
Поправил.

2022-11-02 22:47 UTC, AntonZelinsky commented on bot/messages.py
> +                    logger.error(f'{str(ex.message)}, telegram_id: {user.telegram_id}')
Ошибку нужно логировать во всех случаях.

2022-11-02 22:48 UTC, AntonZelinsky commented on bot/messages.py
> +            break
Брейк не нужен, делай ретурн после успешного вызова

2022-11-03 01:02 UTC, AntonZelinsky commented on bot/messages.py
> +        logger.info("MESSAGE SENT")
Это удали, вообще ничего не говорит

2022-11-03 01:02 UTC, AntonZelinsky commented on bot/messages.py
>                  logger.info(f"Send message to {user.telegram_id}")
А тут send замени на sent.

2022-11-03 01:02 UTC, AntonZelinsky commented on bot/messages.py
> +                if i < tries - 1:
Сложно, это отработает при i=0,1, а при 2, как я понимаю, уже будет работать. -1 не нужен, или я не прав?

2022-11-06 21:01 UTC, kr0t commented on bot/messages.py
> +    def SendBatchMessages(self, user_notification_context):
Не в питоновском стиле название метода.

2022-11-06 21:53 UTC, AntonZelinsky approved these changes

2022-11-06 21:53 UTC, AntonZelinsky commented on bot/messages.py
> +    user_message_context: list
Тут не просто лист, а лист контекстов. Поправь аннотацию.

2022-11-06 21:53 UTC, AntonZelinsky commented on bot/messages.py
> +        user_notification_context = SendUserNotificationsContext(context_list)
Можно ещё проще, сразу создать SendUserNotificationsContext, а потом, в цикле выше добавлять в этот список контексты. Будет красивее и меньше кода.

2022-11-06 21:53 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +                    user_message_context = SendUserMessageContext(message=display_task_notification(task), userid=user.telegram_id)
`display_task_notification(task)` можешь вынести за пределы цика пользователей, чтобы не делать одно и то же действие множество раз.
И в контексте правильно поле назвать не `userid`, а телеграм_айди, так как это немного разные вещи и семантическая ошибка будет. и не забывай про pep8

2022-11-06 21:53 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +                user_notification_context = SendUserNotificationsContext(context_list)
И тоже, создание и добавление контекста хорошо бы вынести выше, как писал в другом фидбеке.

2022-11-06 21:53 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +                notification.SendBatchMessages(user_notification_context)
И эту функцию лучше вызывать с помощью джобы, как было раньше, чтобы приложение успешно завершало свою работу, а рассылка заданий была в фоне. В методе send_notification так же верни как было. Датой старта ставь текущее время, чтобы запуск произошёл сразу, если не сработает, то +1 секунду.

2022-11-06 21:53 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +        time.sleep(10)
Слип должен быть внутри цикла, иначе, это не имеет смысла. и добавь комент зачем это нужно, так как это место будет вызывать множество вопросов в будущем.

А в логе выше замени не на финальный результат, а на процесс отправки, чтобы было `submitting`, так как запустится джоба и процесс выполнения продолжится.

2022-11-07 02:44 UTC, AbramovMax commented on app/webhooks/tasks.py
> +        time.sleep(10)
![image](https://user-images.githubusercontent.com/91040929/200215509-5175f620-a74d-4eb1-a970-5db78c14b2cc.png)
Если перенести тайм слип в цикл, то каждое сообщение будет уходить раз в 10 секунд. Сейчас каждая задача обрабатывается раз в 10 секунд.

2022-11-07 02:58 UTC, AbramovMax commented on app/webhooks/tasks.py
> +                notification.SendBatchMessages(user_notification_context)
![image](https://user-images.githubusercontent.com/91040929/200216022-89c72b0f-7967-4ab2-ad6e-08e047a53557.png)
Сейчас ошибок нет.
Если я снова верну джобы как было раньше, то в текущем коде все сообщения будут отправляться в текущее время, или в текущее время + 1. Что опять вызовет ошибку.
У меня было решение с send_time которое убирало ошибку, но ты попросил поменять его на паузу в секунду в цикле. Обратно возвращать send_time?

Это дизморалит.(((

2022-11-07 09:25 UTC, AbramovMax commented
Вернул джобы и send_time, но на функцию __send_message_context.

Ошибок нет.

2022-11-07 09:44 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +                notification.SendBatchMessages(user_notification_context)
Подожди, ты всё вернул как было, от чего мы с большим трудом избавились. Тебе нужно вызывать в виде джобы метод `notification.send_batch_messages`, который **не должен** принимать время и он ничего не должен возвращать! 
До последний изменений, логика в `send_batch_messages` была вроде как такой, как и должна быть.

2022-11-07 09:46 UTC, AntonZelinsky commented on app/webhooks/tasks.py
> +        time.sleep(10)
Ой, что-то я не понял, а почему раз в 10 секунд каждое сообщение?
Вообще, используя джобы, после правок по другому фидбеку, тут лучше слип заменить на + 10 секунд к `send_time` чтобы асинхронно всё было

![image](https://user-images.githubusercontent.com/1431279/200276458-4db073e1-6cbf-4aa5-966c-9fb2d8e4eba6.png)

2022-11-12 02:02 UTC, AntonZelinsky commented on bot/messages.py
> +        dispatcher.job_queue.run_once(self.send_batch_messages, 1, context=user_notification_context,
А 1 что значит? через одну секунду?

2022-11-12 04:18 UTC, AbramovMax commented on bot/messages.py
> +        dispatcher.job_queue.run_once(self.send_batch_messages, 1, context=user_notification_context,
Да, по документации если в эту штуку передается int, то воспринимается это как шаг в int секунд.

2022-11-12 15:23 UTC, AntonZelinsky commented on bot/messages.py
> +        dispatcher.job_queue.run_once(self.send_batch_messages, 1, context=user_notification_context,
А можно сделать как-то более явно, например `seconds=1`? в целом окей, но со временеим забывается и приходится гадать

2022-11-13 03:44 UTC, AbramovMax commented on bot/messages.py
> +        dispatcher.job_queue.run_once(self.send_batch_messages, 1, context=user_notification_context,
Отдельно назначил переменную seconds перед вызовом джобы.

2022-11-13 21:27 UTC, kr0t approved these changes

2022-11-13 21:28 UTC, merged