Feature/delete root category migration
ProCharity/ProCharity_bot pull request #35
Opened 2022-10-23 10:19 UTC by BuriloT

Создана миграция при применении которой стираются все подписки пользователя на основные категории. 
Если у них есть подкатегории она подписывает пользователя на них.

2022-10-23 20:15 UTC, AntonZelinsky requested changes

2022-10-23 20:15 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +    except ProgrammingError:
Функция называется гет, а в неё что-то удаляется. Не порядок!

Плюс, если во время применения миграции происходит какая-то ошибка, то миграция должна отваливаться, а не успешно завершаться.

2022-10-23 20:15 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +                Users_Categories.category_id != None # noqa
category_id — это праймари кий, он не может быть None!

2022-10-23 20:15 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +                Users_Categories.category_id != None # noqa
Тебе нужно получить все категории, у которых не родителя и уже для их пользователей что-то делать.

2022-10-23 20:15 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +        main_category_id = db_session.scalars(
Сейчас, если в базу 100 пользователей и они подписаны на 10 категорий, а  запросов внутри фора 4 штуки, то ты сделаешь минимум 4000 запросов к базе.
А категорий в базе всего 10 штук! И можно было сделать 40 запросов.

Пока писал пересмотрел код и понял, что там ещё сложенные циклы, что ещё всё делает больше и сложнее.

2022-10-23 20:15 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +        ).all()
Чтобы избавить себя от этих сложностей, можно узнать как [у Ани дела с этой задачкой](https://www.notion.so/Category-be40622f69a04d80a89b99583f0b9448) и если она планирует сделать её сегодня-завтра, то подождать и при заборе категорий забирать и сразу всех потомков, то получится выкинуть все эти дополнительные запросы, всё из одной запроса будет приходить.

Если нет, то оставить todo, что нужно будет переписать позже.

2022-10-23 20:15 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +                    Users_Categories.category_id == main_category_id
Не вижу смысла смотреть дальше, тут какая-то ерунда, нужно всё исправить по фидбекам выше, тогда и это всё будет переписано.

2022-10-30 23:17 UTC, BuriloT commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +    except ProgrammingError:
Я отлавливаю эти ошибки, чтобы при первом применении миграции они все завершились. Есть способ откинуть только мою миграцию?

2022-10-31 01:05 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +    except ProgrammingError:
Есть способ и откатить миграцию, это же просто, нужно из всех потомков перенести записи в родителя категории.
Но вообще, твой код должен быть идемпотентным! То есть, сколько раз его не вызови, он всегда делает одно и то же, ни больше не меньше. В твоей задаче это вообще всё просто делается.

2022-11-01 06:11 UTC, BuriloT commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +    except ProgrammingError:
Неправильно объяснил. Когда создаём базу и применяем к ней все миграции, командой alembic upgrade head без try происходит ошибка т.к. идёт запрос к базе, но в ней нет колонок.

2022-11-06 23:53 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +down_revision = '35477a4b423e'
Убедись, что это указывает на последню миграцию, а то вроде бы Витя что-то делал с миграциями

2022-11-06 23:53 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +        if category.children:
Кажется, что эту проверку можно вынести в sql запрос, напиши чистый sql запрос и потренируйся получать необходимые данные из базы. Потом будет просто переделать.

А вообще, можешь забить) это ведь мирация вызывающаяся один раз, оптимизации тут не так уж и нужны

2022-11-06 23:53 UTC, AntonZelinsky commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +                db_session.add_all(subcategories)
Не нужно вызывать отдельную функцию которая удалит всё и вся! В этом месте у тебя есть вся необходимая информация о родительской категории и пользователе подписанном на неё, просто удаляй тут связь из базы и всё

2022-11-07 04:19 UTC, BuriloT commented on migrations/versions/87c7d29e3ddb_delete_category_insert_subcategory.py
> +                db_session.add_all(subcategories)
Переписал, но теперь удаляет только те родительские категории, у которых есть подкатегории. Ты так это видел?

2022-11-12 15:25 UTC, AntonZelinsky approved these changes

2022-11-14 10:46 UTC, merged